"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Save } from "lucide-react";

type ModelForm = { baseUrl: string; model: string; temperature: string; maxTokens: string };
const defaults: ModelForm = { baseUrl: "https://api.deepseek.com", model: "deepseek-chat", temperature: "0.7", maxTokens: "1200" };

export function ModelSettingsClient() {
  const [form, setForm] = useState(defaults); const [items, setItems] = useState<Array<{ id: string; model: string; baseUrl: string; temperatureMilli: number; maxTokens: number; isActive: boolean; updatedAt: string }>>([]); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/model-settings", { cache: "no-store" }); const payload = await response.json() as { items?: typeof items }; const rows = payload.items ?? []; setItems(rows); const active = rows.find((item) => item.isActive) ?? rows[0]; if (active) setForm({ baseUrl: active.baseUrl, model: active.model, temperature: String(active.temperatureMilli / 1000), maxTokens: String(active.maxTokens) }); }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const response = await fetch("/api/admin/model-settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: "deepseek", baseUrl: form.baseUrl, model: form.model, temperature: Number(form.temperature), maxTokens: Number(form.maxTokens) }) }); setMessage(response.ok ? "模型设置已激活；API Key 继续由服务器环境变量安全管理。" : "保存失败，请检查 HTTPS 地址和数值范围。"); if (response.ok) await load(); }
  return <><header className="admin-header"><div><div className="eyebrow">模型设置</div><h1>DeepSeek 运行参数</h1></div></header><section className="admin-card"><form onSubmit={submit}><div className="form-grid"><div className="field"><label>模型供应商</label><input value="deepseek" disabled /></div><div className="field"><label>Base URL</label><input type="url" required value={form.baseUrl} onChange={(event) => setForm({ ...form, baseUrl: event.target.value })} /></div><div className="field"><label>聊天模型</label><input required value={form.model} onChange={(event) => setForm({ ...form, model: event.target.value })} /></div><div className="field"><label>Temperature（0–2）</label><input type="number" min="0" max="2" step="0.1" value={form.temperature} onChange={(event) => setForm({ ...form, temperature: event.target.value })} /></div><div className="field"><label>最大 Tokens</label><input type="number" min="64" max="32000" value={form.maxTokens} onChange={(event) => setForm({ ...form, maxTokens: event.target.value })} /></div></div><p className="privacy-note">DeepSeek API Key 不在页面中读取或显示，只能通过服务器的 `DEEPSEEK_API_KEY` 环境变量配置。</p><div className="admin-form-actions"><button className="button" type="submit"><Save size={16} />保存并激活</button><span className="form-message" role="status">{message}</span></div></form></section><section className="admin-card" style={{ marginTop: 20 }}><h2>设置历史</h2><div className="table-scroll"><table className="table"><thead><tr><th>模型</th><th>Base URL</th><th>Temperature</th><th>Tokens</th><th>状态</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.model}</td><td>{item.baseUrl}</td><td>{item.temperatureMilli / 1000}</td><td>{item.maxTokens}</td><td><span className={item.isActive ? "chip lime" : "chip"}>{item.isActive ? "当前" : "历史"}</span></td></tr>)}</tbody></table></div></section></>;
}
